server:
  port: 9091

spring:
  application:
    name: MOVIE-FILE-SERVICE
  rabbitmq:
    host: ${RABBITMQ_URL:localhost}
    port: 5672
    username: user
    password: password
    virtual-host: /
  servlet:
    multipart:
      max-file-size: 32GB
      max-request-size: 32GB

virustotal:
  api:
    key: ${VIRUSTOTAL_API_KEY}


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}