server:
  port: 9091
  tomcat:
    connection-timeout: 300s

spring:
  application:
    name: MOVIE-FILE-SERVICE
  rabbitmq:
    host: ${RABBITMQ_URL:localhost}
    port: 5672
    username: user
    password: password
    virtual-host: /
  servlet:
    multipart:
      max-file-size: 32GB
      max-request-size: 32GB
      enabled: true
  mvc:
    async:
      request-timeout: 300000

virustotal:
  api:
    key: ${VIRUSTOTAL_API_KEY}

azure:
  storage:
    connection-string: DefaultEndpointsProtocol=https;AccountName=moviefiledb;AccountKey=${AZUREBLOB_API_KEY};EndpointSuffix=core.windows.net
    container-name: moviefiledb

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}