server:
  port: 9091

spring:
  application:
    name: MOVIE-FILE-SERVICE
  rabbitmq:
    host: ${RABBITMQ_URL:localhost}
    port: 5672
    username: user
    password: password
    virtual-host: /
    servlet:
      multipart:
        max-file-size: 40GB
        max-request-size: 40GB

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}