services:
  EUREKA:
    build:
      context: Eureka
    image: daanvervaecke/watchflix-eureka:latest
    container_name: Eureka
    networks:
      - watchflix-network
    ports:
      - '8761:8761'

  RABBITMQ:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "15672:15672"  # Web management console port
      - "5672:5672"    # AMQP protocol port
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - watchflix-network
    command:
      bash -c "rabbitmq-plugins enable --offline rabbitmq_mqtt && rabbitmq-server"
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_running" ]
      interval: 10s
      timeout: 5s
      retries: 10

  EVENT-BUS:
    build:
      context: EventBus
    image: daanvervaecke/watchflix-eventbus:latest
    container_name: EventBus
    networks:
      - watchflix-network
    ports:
      - '9092:9092'
    depends_on:
      RABBITMQ:
        condition: service_healthy
    environment:
      - RABBITMQ_URL=rabbitmq
      - EUREKA_URL=http://eureka:8761/eureka/

  MOVIE-SERVICE:
    build:
      context: MovieService
    image: daanvervaecke/watchflix-movieservice:latest
    container_name: MovieService
    networks:
      - watchflix-network
    ports:
      - '9090:9090'
    depends_on:
      RABBITMQ:
        condition: service_healthy
    environment:
      - RABBITMQ_URL=rabbitmq
      - EUREKA_URL=http://eureka:8761/eureka/
      - SECRET_KEY_ATLAS

  MOVIE-FILE-SERVICE:
    build:
      context: MovieFileService
    image: daanvervaecke/watchflix-moviefileservice:latest
    container_name: MovieFileService
    networks:
      - watchflix-network
    ports:
      - '9091:9091'
    depends_on:
      RABBITMQ:
        condition: service_healthy
    environment:
      - RABBITMQ_URL=rabbitmq
      - EUREKA_URL=http://eureka:8761/eureka/
      - VIRUSTOTAL_API_KEY
      - AZUREBLOB_API_KEY
        
  USER-SERVICE:
    build:
      context: UserService
    image: daanvervaecke/watchflix-userservice:latest
    container_name: UserService
    networks:
      - watchflix-network
    ports:
      - '9093:9093'
    depends_on:
      RABBITMQ:
        condition: service_healthy
    environment:
      - RABBITMQ_URL=rabbitmq
      - EUREKA_URL=http://eureka:8761/eureka/
      - SECRET_KEY_AES
      - SECRET_KEY_NEON
      - SECRET_KEY_SUPABASE

  GATEWAY:
    build:
      context: Gateway
    image: daanvervaecke/watchflix-gateway:latest
    container_name: Gateway
    networks:
      - watchflix-network
    ports:
      - '8085:8085'
    depends_on:
      RABBITMQ:
        condition: service_healthy
    environment:
      - EUREKA_URL=http://eureka:8761/eureka/
      - JWT_SECRET

  WEBAPP:
    build:
      context: ./Watchflix
    image: daanvervaecke/watchflix-webapp:latest
    container_name: Webapp
    ports:
      - "3000:3000"
    networks:
      - watchflix-network
    depends_on:
      - GATEWAY
    environment:
      - VITE_HOST=http://gateway:8085
      - VITE_SUPABASE_URL=SUPABASE_URL
      - VITE_SUPABASE_ANON_KEY=SECRET_KEY_SUPABASE

networks:
  watchflix-network:
    driver: bridge