services:
  EUREKA:
    build:
      context: Eureka
    image: daanvervaecke/watchflix-eureka:latest
    container_name: Eureka
    networks:
      - watchflix-network
    ports:
      - '8761:8761'

  MOVIE-SERVICE:
    build:
      context: MovieService
    image: daanvervaecke/watchflix-movieservice:latest
    container_name: MovieService
    networks:
      - watchflix-network
    ports:
      - '9090:9090'
    depends_on:
      - EUREKA
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  MOVIE-FILE-SERVICE:
    build:
      context: MovieFileService
    image: daanvervaecke/watchflix-moviefileservice:latest
    container_name: MovieFileService
    networks:
      - watchflix-network
    ports:
      - '9091:9091'
    depends_on:
      - EUREKA
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  GATEWAY:
    build:
      context: Gateway
    image: daanvervaecke/watchflix-gateway:latest
    container_name: Gateway
    networks:
      - watchflix-network
    ports:
      - '8085:8085'
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  WEBAPP:
    build:
      context: ./Watchflix
    image: daanvervaecke/watchflix-webapp:latest
    container_name: Webapp
    ports:
      - "80:80"
    networks:
      - watchflix-network
    depends_on:
      - GATEWAY
    environment:
      - VITE_HOST=http://gateway:8085

networks:
  watchflix-network:
    driver: bridge