apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: movie-file-service
  name: movie-file-service
spec:
  ports:
    - name: "9091"
      port: 9091
      targetPort: 9091
  selector:
    io.kompose.service: movie-file-service
