apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: movie-service
  name: movie-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: movie-service
  template:
    metadata:
      labels:
        io.kompose.service: movie-service
    spec:
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: EUREKA_URL
              value: http://eureka:8761/eureka/
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
            - name: EUREKA_INSTANCE_HOSTNAME
              value: movie-service
          image: daanvervaecke/watchflix-movieservice:latest
          name: movieservice
          ports:
            - containerPort: 9090
              protocol: TCP

      restartPolicy: Always
