server:
  port: 8085
spring:
  application:
    name: GATEWAY
  cloud:
    gateway:
#      globalcors:
#        corsConfigurations:
#          '[/**]':
#            allowedOrigins: "*"
#            allowedMethods:
#              - GET
#              - POST
#              - PUT
#              - DELETE
#            allowedHeaders: "*"
      routes:
        - id: MESSAGE-SERVICE
          -uri: lb://MESSAGE-SERVICE
          predicates:
            - Path=/movieFile/upload
          filters:
            - name: UUIDFilter
        - id: MOVIE-SERVICE
          -uri: lb://MOVIE-SERVICE
          predicates:
            - Path=/movie/**
        - id: MOVIE-FILE-SERVICE
          -uri: lb://MOVIE-FILE-SERVICE
          predicates:
            - Path=/movieFile/**
        - id: USER-SERVICE
          -uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**

jwt:
  secret: ${JWT_SECRET}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}