server:
  port: 8085
spring:
  application:
    name: GATEWAY
  cloud:
    gateway:
      routes:
        - id: MOVIE-SERVICE
          -uri: lb://MOVIE-SERVICE
          predicates:
            - Path=/movie/**
        - id: MESSAGE-SERVICE
          -uri: lb://MESSAGE-SERVICE
          predicates:
            - Path=/movieFile/upload
          filters:
            - name: UUIDFilter
        - id: MOVIE-FILE-SERVICE
          -uri: lb://MOVIE-FILE-SERVICE
          predicates:
            - Path=/movieFile/**

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}