server:
  port: 9093

spring:
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:postgresql://ep-lucky-grass-a9wgm1jy-pooler.gwc.azure.neon.tech/userdb
    username: userdb_owner
    password: ${SECRET_KEY_NEON}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      # Prevent Hibernate from automatically modifying the schema (since Flyway)
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
  #  rabbitmq:
#    host: ${RABBITMQ_URL:localhost}
#    port: 5672
#    username: user
#    password: password
#    virtual-host: /

encryption:
  secret-key: ${SECRET_KEY_AES}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}