server:
  port: 9093

spring:
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:postgresql://ep-lucky-grass-a9wgm1jy-pooler.gwc.azure.neon.tech/userdb
    username: userdb_owner
    password: ${SECRET_KEY_NEON}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate # Prevent Hibernate from automatically modifying the schema (since Flyway)
  flyway:
    enabled: true
    locations: classpath:db/migration

supabase:
  url: https://dncoimjidifbzrifcvsk.supabase.co
  service:
    key: ${SECRET_KEY_SUPABASE}

encryption:
  secret-key: ${SECRET_KEY_AES}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}