#apiVersion: autoscaling/v2
#kind: HorizontalPodAutoscaler
#metadata:
#  name: movie-file-service-hpa
#spec:
#  scaleTargetRef:
#    apiVersion: apps/v1
#    kind: Deployment
#    name: movie-file-service
#  minReplicas: 1
#  maxReplicas: 4
#  metrics:
#    - type: Resource
#      resource:
#        name: cpu
#        target:
#          type: Utilization
#          averageUtilization: 50