apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: user-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user-service
  minReplicas: 1
  maxReplicas: 20
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
  #  For more stable scaling
#  behavior:
#    scaleUp:
#      stabilizationWindowSeconds: 180
#      policies:
#        - type: Pods
#          value: 1
#          periodSeconds: 180
#    scaleDown:
#      stabilizationWindowSeconds: 60