server:
  port: 9090

spring:
  application:
    name: MOVIE-SERVICE
  data:
    mongodb:
      uri: mongodb+srv://daanvvc:${SECRET_KEY_ATLAS}@watchflix.xalddl7.mongodb.net
      database: watchflix
  rabbitmq:
    host: ${RABBITMQ_URL:localhost}
    port: 5672
    username: user
    password: password
    virtual-host: /

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}