server:
  port: 9090

spring:
  application:
    name: MOVIE-SERVICE
  rabbitmq:
    host: ${RABBITMQ_URL:localhost}
    port: 5672
    username: user
    password: password
    virtual-host: /

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}