# Setup of RabbitMQ container
version: '4.0'
services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq_test
    ports:
      - "15672:15672"  # Web management console port
      - "5672:5672"    # AMQP protocol port
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    command:
      bash -c "rabbitmq-plugins enable --offline rabbitmq_mqtt && rabbitmq-server"